### ISSUE TITLE
Add upcheck for workers (intergiro acquirer)

### ISSUE THREAD

**Issue by robinnedergard** [payfunc/upcheck#11]
- [ ] https://github.com/payfunc/cli/pull/45
- [ ] https://github.com/payfunc/cli/pull/44
- [x] https://github.com/payfunc/cli-card/pull/58
- [x] https://github.com/payfunc/cli-card/pull/59
